SCANNERS_TOPIC = 'room_presence/'
LONG_DELAY_PENALTY_SEC = 50
TURN_OFF_DEVICE_SEC = 180
HEARTBEAT_COLLECT_PERIOD_SEC = 5
DEVICE_CHANGE_STATE_BEATS = 5
DEVICE_CHANGE_STATE_SECONDS = 10
KALMAN_R = 0.15
KALMAN_Q = 10.0
