SCANNERS_TOPIC = 'room_presence/'
LONG_DELAY_PENALTY_SEC = 110
TURN_OFF_DEVICE_SEC = 150
HEARTBEAT_COLLECT_PERIOD_SEC = 2
DEVICE_CHANGE_STATE_BEATS = 10
DEVICE_CHANGE_STATE_SECONDS = 15
KALMAN_R = 0.15
KALMAN_Q = 10.0
